# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [3]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
print("An array of 10 zeros:", np.zeros(10))

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
import numpy as np
n = np.zeros(10) 
n = n.astype(int)
n

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
print("An array of 10 fives:", np.ones(10)*5)

An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [12]:
print("An array of all the even integers from 20 to 35: " , np.arange(20,35,2))

An array of all the even integers from 20 to 35:  [20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
print(np.arange(0, 9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[5 7 9]


In [15]:
n = np.concatenate((a,b),axis=None)
n

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [16]:
import pandas as pd

ImportError: cannot import name 'DtypeObj' from 'pandas._typing' (C:\Users\ADMIN\Anaconda3\lib\site-packages\pandas\_typing.py)

In [ ]:
data = {'Name': ['Abisha', 'Guvishii', 'Prakash'],
        'Age': [19, 20, 21]}
df = pd.DataFrame(data)
df

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
date = pd.date_range(start='10-03-2023',end='15-05-2023')
for val in date:
  print(val)

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [20]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
df2 = pd.DataFrame(lists, columns =['S.No', 'Name', 'Age']) 
print(df2)

   S.No Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
